version: '3'
services:
  postgres:
    image: postgres:16.0
    ports:
     #端口自行替换本文使用默认端口
     - "5432:5432"
    volumes:
     #数据文件本地的存放位置（启动后会在当前目录下创建mount，用来存放数据库文件）
     - ./data/db:/var/lib/postgresql/data
     - ./data/db/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
     - PGDATA=/var/lib/postgresql/data/pgdata
     #用户名 可自行更改
     - POSTGRES_USER=postgresuser
     #密码 可自行更改
     - POSTGRES_PASSWORD=postgrespw
     - POSTGRES_DB=elearning
  # 添加 pgadmin4
  pgadmin:
    image: dpage/pgadmin4:7.8
    ports:
     #端口自行替换本文使用默认端口
     - "5050:80"
    environment:
     #用户名 可自行更改
     - PGADMIN_DEFAULT_EMAIL=user@domain.com
     - PGADMIN_DEFAULT_PASSWORD=SuperSecret"