server:
  address: 0.0.0.0
  port: 3000
  prefix: /api/v1
# Postgres 数据库配置

database:
  type: postgres
  host: 127.0.0.1
  port: 5432
  user: postgresuser
  password: postgrespw
  dbname: elearning

jwt:
  secret: jwtsecret
